### PR TITLE
Wardrobe & Figure manager

### PR DESCRIPTION
**Pull request by IDjinn**
- [x] Removed the key of user_wardrobe table, now user_id and slot_id are unique indexes
- [x] FigureValidation
  - [x] Read xml and insert into db
  - [x] Read from db and storage in cache valid figure sets
  - [x] Process figure raw string and check if it's valid or not
  - [x] Assign default figure for required parts (head, body etc)

TODO: when ClothingComponent will be refractored need update `FigureDataManager.ValidateFigure` logic

### CODE REVIEW

**Comment by IDjinn** [comment]
Should `_figureDataManager.ProcessFigure` moved into wardrobe manager logic?

**Comment by 80O** [comment]
I would create a FigureValidator class and rename the process method to Validate

**Comment by IDjinn** [comment]
Yeah, I thought same. But if i touch that will need refract 😆 

I will do soon

**Comment by DamienJolly** [comment]
I quite like the plus validator, but all the figure parts and colours should be stored in the database (similar to item_data -> furnidata). Then we can avoid loading in the xml file.

The only downside to this is that when you add new clothing you'll have to add a new entry into the database, but I don't see this being too much off an issue since its already done for items.

Imo, furnidata, figuredata ext should all be auto generated from the database anyway.

**Comment by 80O** [comment]
I would follow Damiens suggestion and move all the xml stuff to the database.
Add a command (console & room & rcon) to generate the XML files.
For nitro we probably would have to generate some json files right?

**Comment by IDjinn** [comment]
> For nitro we probably would have to generate some json files right?

I have no clue how nitro assets work, I appreciate help when need do that

**Comment by McFluffy** [comment]
> 

It's probably not best to handle generating the XML/nitro files in the scope of the emulator. This functionality is best suited as a plugin or another external program.

**Comment by 80O** [comment]
If we were to host it in the database for figure validation; anyone who runs this emulator has to rely on this feature or do the modifications twice.

Also there is no plugin system yet.

**Comment by IDjinn** [comment]
Done.

**Comment by IDjinn** [comment]
Outdated

**Pull request closed without merging**
