### PR TITLE
Fix for the #44

### PR DESCRIPTION
**Pull request by TheMathys**
i think this is a client issue #44

### CODE REVIEW

**Comment by DamienJolly** [comment]
Sorry, what does this solve actually? I'm failing to see how this fix does anything. (No offence)

**Review by DamienJolly — COMMENTED** [review]
If we're emulating Habbo as close as possible, this is not the intended way. Habbos offline friends don't display the users figures. Maybe this should be a configurable option?

**Review by DamienJolly — COMMENTED** [review]
Sorry, what does this solve actually? I'm failing to see how this fix does anything. (No offence)

**Comment by DamienJolly** [comment]
> The issue is that the openflatconnection packet is received 3 times

This fix doesn't fix this issue you're referring too, did you test this fix?

**Comment by TheMathys** [comment]
> This fix doesn't fix this issue you're referring too, did you test this fix?
Yes i test this, it works. You can log the isLoadingRoom it will log True then False and False. This is a SWF issue.

**Comment by 80O** [comment]
I think there is probably an underlying issue of the client being forwarded to the same room multiple times. I think that should be addressed instead of trying to resolve it this way.

**Comment by 80O** [comment]
Closing for now. Feels like a hack and not resolving the underlying issue that causes this method to be executed multiple times.

**Pull request closed without merging**
